;
; MACHINE LANGUAGE MODULE FOR chngfont.c
;
_AOFF EQU 6 ; STACK OFFSET TO FIRST ARG
_TEXT SEGMENT BYTE PUBLIC 'CODE'
ASSUME CS:_TEXT.DS:_DATA
; REPROGRAM THE FONT CONTROLLER
; ARG1 = POINTER TO NEW FONT [0]
; ARG2 = FIRST CHARACTER [4]
; ARG3 = NUMBER OF CHARACTERS [6]
; ARG4 = POINTS [8]
; ARG5 = BLOCK [10]
PUBLIC _DownloadFont
_DownloadFont PROC FAR
PUSH BP
MOV BP,SP
PUSH DS
PUSH ES
MOV AX,1110H
MOV BH,BYTE PTR[BP + _AOFF + 8]
MOV BL,BYTE PTR[BP + _AOFF + 10]
AND BL,07H
MOV CX,[BP + _AOFF + 6]
MOV DX,[BP + _AOFF + 4]
MOV ES,[BP + _AOFF + 2]
MOV BP,[BP + _AOFF + 0]
INT 10H
POP DS
POP ES
POP BP
RET
_DownloadFont ENDP
_TEXT ENDS
DGROUP GROUP _DATA, _BSS
_DATA SEGMENT WORD PUBLIC 'DATA'
_DATA ENDS
_BSS SEGMENT WORD PUBLIC 'BSS'
_BSS ENDS
END
